steps:
  # Build tghe cintainer image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 't', 'us-central1-docker.pkg.dev/cloud-factory1/cloud-factory1-docker-repo/cloud-factory1-gcr-image:tag1', '.']

  # PUSH the container image to the Artifacts registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/cloud-factory1/cloud-factory1-docker-repo/cloud-factory1-gcr-image:tag1']
  
  # Deploy container image to google cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-factory1-gcr-image', --'image', 'us-central1-docker.pkg.dev/cloud-factory1/cloud-factory1-docker-repo/cloud-factory1-gcr-image:tag1', '--region','us-central1']
images:
- 'us-central1-docker.pkg.dev/cloud-factory1/cloud-factory1-docker-repo/cloud-factory1-gcr-image:tag1'




