import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CloudFactory.cloud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-700">
        <div className="border-2 border-green-500 h-screen">
          <div className="border-2 border-red-500">Top Nav</div>
          <div className="border-2 border-blue-500">
            <div>Side Nav</div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
